version: '3.6'
services:

  app:
    build:
      context: docker/php-fpm
      args:
        UID: ${DOCKER_UID}
        GID: ${DOCKER_GID}
    entrypoint: sh -c "composer install"
    env_file:
      - ./app/.env
    volumes:
      - ./:/www
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db

  nginx:
    build: docker/nginx
    depends_on:
      - app
    ports:
     - 80:80
    volumes:
      - ./:/www
      - ./docker/nginx/development.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
      - ./dumps:/home
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${DOCKER_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_DATABASE}
      - MYSQL_USER=${DOCKER_USERNAME}
      - MYSQL_PASSWORD=${DOCKER_PASSWORD}

volumes:
  database: